from __future__ import annotations

from typing import Any, Protocol


class Scene(Protocol):
    """Optional lifecycle/render/input contract for project runtime scenes."""

    def enter(self) -> None: ...
    def exit(self) -> None: ...
    def pause(self) -> None: ...
    def resume(self) -> None: ...
    def update(self, dt: float) -> None: ...
    def handle_input(self, event: Any) -> bool: ...
    def render(self, target: Any) -> None: ...
    def serialize(self) -> dict[str, Any]: ...
    def deserialize(self, payload: dict[str, Any]) -> None: ...
