name: package
on:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m pip install -e . pyinstaller
      - shell: bash
        run: python tools/build.py examples/demo --name PyNovelDemo
      - uses: actions/upload-artifact@v4
        with:
          name: PyNovelDemo-${{ matrix.os }}
          path: dist/
